// Generated by https://quicktype.io

export interface User {
    _id:         string;
    name:        string;
    description: string;
    email:       string;
    password:    string;
    createdAt:   string;
    updatedAt:   string;
}
